# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
common: &common
  adapter: postgresql
  username: postgres
  password: shaina # from psql setup, see Postgresql

development:
  <<: *common
  database: wtadb


production:
  <<: *common
  database: myapp_production